Repository aaronmallen/activeinteractor, pull requests merged in 2020-10, with the labels that each got.

#248 generate the v1.1.0 release
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/active_interactor/context/attributes.rb
  lib/active_interactor/organizer/interactor_interface.rb
  lib/active_interactor/version.rb
Labels: release

#253 Refactor ActiveInteractor::VERSION
  .gitignore
  Gemfile.lock
  activeinteractor.gemspec
  lib/active_interactor/version.rb
  spec/active_interactor_spec.rb
Labels: bugfix

#254 #251 ensure ActiveInteractor is loaded
  activeinteractor.gemspec
Labels: bugfix

#259 ensure correct branch name is returned to codeclimate
  .github/workflows/ci.yml
Labels: codeclimate

#265 updated SECURITY.md
  SECURITY.md
Labels: docs

#266 added the security_report issue template
  .github/ISSUE_TEMPLATE/security_report.md
  SECURITY.md
Labels: docs

#274 added ActiveInteractor::Interactor::State
  lib/active_interactor.rb
  lib/active_interactor/interactor/state.rb
  spec/active_interactor/interactor/state_spec.rb
Labels: feature

#267 Allow default attributes to propagate to child/sibling interactors
  lib/active_interactor/context/attributes.rb
  spec/integration/a_basic_organizer_spec.rb
Labels: bugfix, hacktoberfest-accepted

#279 cherry pick @mohameddiaa27 changes to main
  lib/active_interactor/context/attributes.rb
  spec/integration/a_basic_organizer_spec.rb
Labels: bugfix

#280 generate the v1.1.1 release
  CHANGELOG.md
  Gemfile.lock
  lib/active_interactor/version.rb
Labels: release

#278 added ActiveInteractor::Interactor::Result
  lib/active_interactor.rb
  lib/active_interactor/interactor/result.rb
  lib/active_interactor/interactor/state.rb
  spec/active_interactor/interactor/result_spec.rb
  spec/active_interactor/interactor/state_spec.rb
Labels: feature

#282 various document updates and build improvements
  .github/workflows/lint.yml
  CONTRIBUTING.md
  Gemfile
  HUMANS.md
  README.md
  bin/rubocop
Labels: docs

#284 drop bug support for 1.0.x
  SECURITY.md
Labels: docs

#286 #217 interactor failure hooks
  lib/active_interactor/interactor/callbacks.rb
  lib/active_interactor/interactor/worker.rb
  spec/support/shared_examples/a_class_with_interactor_callback_methods_example.rb
Labels: feature

#288 Deprecation
  lib/active_interactor.rb
  lib/active_interactor/config.rb
  lib/active_interactor/deprecation.rb
  spec/active_interactor/config_spec.rb
  spec/active_interactor/deprecation_spec.rb
Labels: feature

#289 #270 Result method_missing
  lib/active_interactor/interactor/result.rb
  spec/active_interactor/interactor/result_spec.rb
Labels: bugfix

#290 #270 ensure interactor returns a ActiveInteractor::Interactor::Result
  lib/active_interactor/context/attributes.rb
  lib/active_interactor/interactor/context.rb
  lib/active_interactor/interactor/perform.rb
  lib/active_interactor/interactor/result.rb
  lib/active_interactor/models.rb
  lib/active_interactor/organizer/interactor_interface.rb
  lib/active_interactor/organizer/perform.rb
  spec/active_interactor/interactor/worker_spec.rb
  spec/active_interactor/organizer/base_spec.rb
  spec/integration/a_basic_interactor_spec.rb
  spec/integration/a_basic_organizer_spec.rb
  spec/integration/a_failing_interactor_spec.rb
  spec/integration/an_interactor_with_after_context_validation_callbacks_spec.rb
  spec/integration/an_interactor_with_after_perform_callbacks_spec.rb
  spec/integration/an_interactor_with_after_rollback_callbacks_spec.rb
  spec/integration/an_interactor_with_an_existing_context_class_spec.rb
  spec/integration/an_interactor_with_around_perform_callbacks_spec.rb
  spec/integration/an_interactor_with_around_rollback_callbacks_spec.rb
  spec/integration/an_interactor_with_before_perform_callbacks_spec.rb
  spec/integration/an_interactor_with_before_rollback_callbacks_spec.rb
  spec/integration/an_interactor_with_validations_on_called_spec.rb
  spec/integration/an_interactor_with_validations_on_calling_spec.rb
  spec/integration/an_interactor_with_validations_spec.rb
  spec/integration/an_organizer_performing_in_parallel_spec.rb
  spec/integration/an_organizer_with_after_each_callbacks_spec.rb
  spec/integration/an_organizer_with_around_each_callbacks_spec.rb
  spec/integration/an_organizer_with_before_each_callbacks_spec.rb
  spec/integration/an_organizer_with_conditionally_organized_interactors_spec.rb
  spec/integration/an_organizer_with_failing_nested_organizer_spec.rb
  spec/integration/an_organizer_with_options_callbacks_spec.rb
  spec/support/shared_examples/a_class_that_extends_active_interactor_models_example.rb
  spec/support/shared_examples/a_class_with_interactor_context_methods_example.rb
Labels: feature
